# SPDX-FileCopyrightText: PyPSA Contributors
# SPDX-License-Identifier: MIT
**
!.git/
!.git/**
!pyproject.toml
!README.md
!LICENSE
!LICENSES/
!LICENSES/**
!MANIFEST.in
!pypsa/
!pypsa/**
!server/
!server/**
!examples/
!examples/networks/
!examples/networks/ac-dc-meshed/
!examples/networks/ac-dc-meshed/ac-dc-meshed.nc
**/.env*
**/.venv
**/__pycache__
**/*.pyc
**/.pytest_cache
**/.ruff_cache
**/*.egg-info
